# Data Preprocessing 
We're gonna create a proper tf.data.Dataset object with an iterator (cause otherwise it won't fit in memory).
To do that we need to scale the inputs, both the image and the labels.
Since the output of the network is like *13x13x3x(4+1+num_classes)* we also need to format our ground truth into such a matrix first, in order to calculate the loss function (more or less).

In [3]:
# Importing main packages
import numpy as np
import tensorflow as tf

In [4]:
BATCH_SIZE = 32
IMG_DIMENSION = 1280
SCALE = 1
# GRID SIZE
SMALL = 40
MEDIUM = 80
LARGE = 160

In [5]:
yolo_anchors = tf.constant([(10, 10), (22, 23), (47, 33), (39, 81), (82, 54), (127, 86),
                         (118, 168), (194, 130), (257, 221)], tf.float32) / IMG_DIMENSION
masks = [[0,1,2],
         [3,4,5],
         [6,7,8]]

## Prepocessor object
We're gonna define a Preprocessor Object that *grey pad* the image and resize it to be a square, and preprocess the labels accordingly.
Note that in input pipelines eager mode is not available even in TF 2.x! 

In [6]:
class Preprocess:
    def __init__(self, num_classes = 10, output_dimension = 1280, training = True):
        self.num_classes = num_classes
        self.output_dimension = output_dimension
        self.training = training
        
    def __call__(self, image_path):
        '''
        INPUT: the path of the image i want to preprocess
        OUTPUTS: a Tensor if training is false
                 a Tuple of (1280x1280, (35x35x3x15, 70x70x3x15, 140x140x3x15))
                            (Image, Ground Truth)
        '''
        img = self.load_img(image_path)
        label = self.load_label(image_path)
        img, label = self.resize_img_n_label(img, label)
        
        output = (img, (self.preprocess_label_for_one_scale('large', label),
              self.preprocess_label_for_one_scale('medium', label),
              self.preprocess_label_for_one_scale('small', label)))

        return output
    

    def preprocess_label_for_one_scale(self, grid_size, label):        
        if grid_size == 'small':
            grid_size = SMALL
            idx = 0
        elif grid_size == 'medium':
            grid_size = MEDIUM
            idx = 1
        elif grid_size == 'large':
            grid_size = LARGE
            idx = 2
        else: raise ValueError('expected small, medium or large')
            
        #those are the indices in which i'll place the label
        cell = tf.cast(label[..., :2]*grid_size,tf.int64)
        anc = self.find_best_anchor(label)
        mask = tf.equal(anc // 3, idx)
        anc = anc % 3
        cell = tf.concat([cell, tf.expand_dims(anc, 1)], 1)
        cell_filtered = tf.boolean_mask(cell, mask, axis = 0)
        label_filtered = tf.boolean_mask(label, mask, axis = 0)
        ### getting x,y relative values to cell borders
        label_filtered = tf.concat([label_filtered[..., :2]*grid_size - tf.floor(label_filtered[..., :2]*grid_size), label_filtered[..., 2:]], 1)
        pro_label = tf.scatter_nd(cell_filtered, label_filtered, [grid_size, grid_size, 3, 15])
        
        return pro_label

    def resize_img_n_label(self, img, label):
        img = tf.image.resize_with_pad(img, 1280, 1280)
        img = img / 255
        
        y_shift = (1280-720)/2
        new_label = tf.stack([label[..., 0], label[..., 1]+y_shift], 1)
        new_label = tf.concat([new_label, label[..., 2:]], 1)
        label = tf.concat([new_label[..., 0:4]/IMG_DIMENSION, new_label[..., 4:]], axis = 1)

        return img, label
    
    def find_best_anchor(self, bb, anchors = yolo_anchors):
        ## assuming bb is like [x,y,w,h]
        bb = bb[..., 2:4]
        bb = tf.expand_dims(bb, 1)
        ## we can just assume all anchors and the ground truth box share the same centroid. And with this assumption
        ## the degree of matching would be the overlapping area, which can be calculated by min width * min height.
        intersection = tf.math.minimum(anchors, bb)
        intersection = intersection[..., 0] * intersection[..., 1]
        union = anchors[..., 0] * anchors[..., 1] + bb[..., 0] * bb[..., 1] - intersection
        broadcast_IoU = intersection/union
        best_one = tf.math.argmax(broadcast_IoU, 1)
        
        return best_one

############## Loading images and labels
    
    def load_img(self, img_path):
        img = tf.io.read_file(img_path)
        img = tf.image.decode_jpeg(img, channels=3) #(720, 1280, 3)
        return img
    
    def load_label(self, img_path):
        # Get the right path
        label_path = self.get_label_path(img_path)
        # Load the file and shape it
        label = tf.io.read_file(label_path)
        label = tf.io.decode_raw(label, tf.int16)
        label = tf.cast(label,tf.float32)
        label = tf.reshape(label, [-1, 15])
        return label
    
    def get_label_path(self, img_path):
        parts = tf.strings.split(img_path, sep = '/images/100k/train/')
        label_path = tf.strings.join([parts[0], '/labels/train_label_raw/', parts[1], '.rawlabel'])
        return label_path
        
        
        

## Creating the Dataset
Now that we have a fully TF mapping function without any loop we're ready to create a dataset

In [7]:
def create_dataset(global_path, batch = 32):
    dataset = tf.data.Dataset.list_files([global_path])
    mapping_func = Preprocess()
    dataset = dataset.map(mapping_func)
    if batch == 1:
        return dataset.prefetch(1)
    dataset = dataset.batch(32).prefetch(1)
    return dataset

# imgdir = '/home/andrea/AI/ispr_yolo/data/dataset_bdd/images/100k' + '/train/*.jpg'
# dataset = tf.data.Dataset.list_files([imgdir])
# mapping_func = Preprocess()
# dataset = dataset.map(mapping_func)
# dataset = dataset.batch(32).prefetch(1)

# val_size = int(7000)
# train_ds = dataset.skip(val_size)
# val_ds = dataset.take(val_size)

# print(train_ds)
# print(val_ds)
def generate_two_label_example(batch = False):
    dataset = create_dataset('/home/andrea/AI/ispr_yolo/data/dataset_bdd/images/100k' + '/train/*.jpg', batch=1)
    labels = []
    for item in dataset.take(1):
        img, label = item
#         labels.append(label)
#         print(label[2])
        print(img)
        tf.print(img[600:603,600:603,...])
generate_two_label_example()

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(1280, 1280, 3), dtype=float32)
[[[0.458823532 0.505882382 0.490196079]
  [0.498039216 0.556862772 0.53725493]
  [0.447058827 0.494117647 0.478431374]]

 [[0.56078434 0.607843161 0.592156887]
  [0.509803951 0.556862772 0.541176498]
  [0.360784322 0.407843143 0.392156869]]

 [[0.568627477 0.615686297 0.6]
  [0.494117647 0.541176498 0.525490224]
  [0.352941185 0.4 0.384313732]]]


In [10]:
image_path = '/home/andrea/AI/ispr_yolo/data/dataset_bdd/images/100k/train/5823b731-7716da84.jpg'
prep = Preprocess()
img = prep.load_img(image_path)
label = prep.load_label(image_path)
print('raw label:')
tf.print(label)
img, label = prep.resize_img_n_label(img, label)
cell = tf.cast(label[..., :2]*40,tf.int64)

anc = prep.find_best_anchor(label)

mask = tf.equal(anc // 3, 0)
anc = anc % 3

cell = tf.concat([cell, tf.expand_dims(anc, 1)], 1)

cell_filtered = tf.boolean_mask(cell, mask, axis = 0)
print('\n indices after padding')
tf.print(cell_filtered)
label_filtered = tf.boolean_mask(label, mask, axis = 0)
label_filtered = tf.concat([label_filtered[..., :2]*40 - tf.floor(label_filtered[..., :2]*40), label_filtered[..., 2:]], 1)
print('\n actual values in target')
tf.print(label_filtered)
pro_label = tf.scatter_nd(cell_filtered, label_filtered, [40, 40, 3, 15])
tf.print(pro_label[31,14,1, ...], summarize = 20)

raw label:
[[402 212 12 ... 0 0 0]
 [862 169 22 ... 0 0 0]
 [999 169 14 ... 0 0 0]
 ...
 [112 326 112 ... 1 0 0]
 [1126 404 153 ... 1 0 0]
 [573 196 131 ... 0 0 0]]

 indices after padding
[[12 15 0]
 [26 14 0]
 [31 14 1]
 ...
 [7 16 1]
 [13 16 0]
 [34 17 2]]

 actual values in target
[[0.5625 0.375 0.009375 ... 0 0 0]
 [0.9375 0.03125 0.0171875 ... 0 0 0]
 [0.21875 0.03125 0.0109375 ... 0 0 0]
 ...
 [0.625 0.6875 0.0203125 ... 1 0 0]
 [0.6875 0.78125 0.00625 ... 1 0 0]
 [0.15625 0.375 0.0328125 ... 1 0 0]]
[0.21875 0.03125 0.0109375 0.025 1 0 0 1 0 0 0 0 0 0 0]
